routes/web.php
    Route::resource('/employee/nominee','NomineeController',['except'=>['index','show']]);
    Route::resource('/employee/workexpericence','WorkingExperienceController',['except'=>['show']]);
    Route::resource('/employee/skill','SkillTestController',['except'=>['show']]);
    Route::get('/employee/workexperience/delete/{id}','WorkingExperienceController@showDelete')->name('workexperience.delete.show');
    Route::get('/employee/skill/delete/{id}','SkillTestController@showDelete')->name('skill.delete.show');
    Route::get('/employee/nominee/delete/{id}','NomineeController@showDelete')->name('nominee.delete.show');
    Route::get('/employee/training/delete/{id}','EmployeeTrainingController@showDelete')->name('training.delete.show');
    Route::resource('/employee/attachments','OtherAttachmentController',['except'=>['create','index']]);
    Route::patch('/employee/password/{id}','EmployeeController@UpdatePassword')->name('employee.password.update');
    Route::patch('/employee/photo/{id}','EmployeeController@UpdatePhoto');
//    Route::get('/employee/floor/line/{id}','EmployeeController@floor_line');
    Route::get('/employeelist/continuedAbsentList',['middleware'=>'check-permission:admin|hr','uses'=>'EmployeeController@getContinueAbsentList'])->name('employee.continued_absent_list');
    Route::post('/report/continuedAbsentListNotification',['middleware'=>'check-permission:admin|hr','uses'=>'EmployeeController@continueAbsentEmployeeNotification']);
    Route::get('section-autocomplete-ajax',array('as'=>'employee.section.autocomplete.ajax','uses'=>'EmployeeController@sectionAjaxData'));
    Route::POST('/store_medical_history',['middleware'=>'check-permission:admin|hr|executive','uses'=>'EmployeeController@store_medical_history']);
    Route::patch('/update_medical_history/{id}','EmployeeController@update_medical_history');
    Route::get('/employee_medical_history_pdf/{id}',['middleware'=>'check-permission:admin|hr|executive','uses'=>'EmployeeController@download_ems'])->name('employee.download_ems');
  
    Route::get('/AbsentEmployees/sendAutoSMS','EmployeeController@sent_auto_sms')->name('employee.continue_absent_list_autosms');
    Route::get('/retire/employee/list',['middleware'=>'check-permission:admin|hr|executive','uses'=>'EmployeeController@retired_list']);
    //Employee Route End
    //Settings route start
    Route::get('/user_settings',['middleware'=>'check-permission:admin|hr','uses'=>'SystemsettingsController@index']);
    Route::post('/user_update',['middleware'=>'check-permission:admin|hr','uses'=>'SystemsettingsController@user_pass_update']);
    Route::resource('/settings/country','CountryController',['except'=>['show','create','edit']]);
    Route::resource('/settings/maritialstatus','MaritialStatusController',['except'=>['show','create','edit']]);
    Route::resource('/settings/department','DepartmentController',['except'=>['show','create','edit']]);
    Route::resource('/settings/designation','DesignationController',['except'=>['show','create','edit']]);
    Route::resource('/settings/unit', 'UnitController',['except'=>['create']]);
    Route::resource('/settings/overtime','OvertimeController',['except'=>['create','store','show','edit','destroy']]);
    Route::get('/settings/unit/delete/show/{id}',['middleware'=>'check-permission:admin|hr','uses'=>'UnitController@showDelete'])->name('unit.delete.show');
    // Settings route end
    //recruitment Route Start
    Route::resource('/recruitment/vacancy','RecruitmentController',['except'=>'edit']);
    Route::get('/recruitment/application/create','RecruitmentController@vacancyApplication')->name('application.create');
    Route::post('/recruitment/application','RecruitmentController@storeVacancyApplication')->name('application.store');
    Route::get('/recruitment/application','RecruitmentController@indexVacancyApplication')->name('application.index');
    Route::get('/recruitment/status','RecruitmentController@dailyRecruitment')->name('recruitment.status');
    Route::get('/recruitment/status/{date}', 'RecruitmentController@recruitmentStatus');
    Route::get('/recruitment/application/{id}', 'RecruitmentController@detailsVacancyApplication')->name('application.details');
    Route::patch('/recruitment/application/{id}','RecruitmentController@applicationUpdate')->name('application.update');
    Route::delete('/recruitment/application/{id}','RecruitmentController@applicationDelete')->name('application.delete');
    //recruitment Route end
    //payroll Route Start
    Route::get('/report/employee/daily/salary',['middleware'=>'check-permission:admin|hr','uses'=>'SalarySheet@employeeDailysalary']);
    Route::post('/report/employee/daily/salary/show',['middleware'=>'check-permission:admin|hr','uses'=>'SalarySheet@employeeDailysalaryshow']);
    Route::get('/employee/grade/salary/update/{id}',['middleware'=>'check-permission:admin|hr','uses'=>'SalaryController@gradeWisesalaryUpdate']);
    Route::get('/employee/salary/grade/modals/{id}',['middleware'=>'check-permission:admin|hr','uses'=>'SalaryController@employeeSalaryEditmodal']);
    Route::post('/deduction_overtime',['middleware'=>'check-permission:admin|hr','uses'=>'PayrollController@employee_absent_overtime']);
    Route::post('/payroll_grade_store',['middleware'=>'check-permission:admin|hr','uses'=>'PayrollController@payroll_grade_store']);
    Route::get('/payroll/grade',['middleware'=>'check-permission:admin|hr','uses'=>'PayrollController@payroll_grade']);
    Route::get('/payslip',['middleware'=>'check-permission:admin|hr','uses'=>'PayrollController@payslip']);
    Route::get('/grade',['middleware'=>'check-permission:admin|hr','uses'=>'PayrollController@payroll_grade_show']);
    Route::post('/grade_update',['middleware'=>'check-permission:admin|hr','uses'=>'PayrollController@payroll_grade_update']);
    Route::get('/grade_delete/{id}',['middleware'=>'check-permission:admin|hr','uses'=>'PayrollController@grade_delete']);
    Route::get('/salary_list',['middleware'=>'check-permission:admin|hr','uses'=>'SalaryController@total_salary_view']);
    Route::get('/salary',['middleware'=>'check-permission:admin|hr','uses'=>'PayrollController@payroll_salary']);
    Route::post('/gradeajax/{id}',['middleware'=>'check-permission:admin|hr','uses'=>'PayrollController@show']);
    Route::post('/salary_store',['middleware'=>'check-permission:admin|hr','uses'=>'SalaryController@store']);
    Route::get('/salary_view',['middleware'=>'check-permission:admin|hr','uses'=>'SalaryController@index']);
    Route::post('/salary_up',['middleware'=>'check-permission:admin|hr','uses'=>'SalaryController@update']);
    Route::get('/payroll/salary',['middleware'=>'check-permission:admin|hr','uses'=>'PayrollController@payroll_salary']);
    Route::post('/employee/bonus/store',['middleware'=>'check-permission:admin|hr','uses'=>'PayrollController@bonus_emloyee']);
    Route::post('/overtime_employee',['middleware'=>'check-permission:admin|hr','uses'=>'PayrollController@employee_overtime']);
    Route::post('/overtime_employee_store',['middleware'=>'check-permission:admin|hr','uses'=>'PayrollController@overtime_amount_hour_store']);
    Route::post('/festivalbonus',['middleware'=>'check-permission:admin|hr','uses'=>'PayrollController@empFestivalbonus']);
    Route::post('/leave_employee',['middleware'=>'check-permission:admin|hr','uses'=>'PayrollController@leave_employee']);
    Route::post('/pres_employee',['middleware'=>'check-permission:admin|hr','uses'=>'PayrollController@employee_present_days_count']);
    Route::post('/leave_employee_store',['middleware'=>'check-permission:admin|hr','uses'=>'PayrollController@leave_employee_store']);
    Route::post('/employee_present_store',['middleware'=>'check-permission:admin|hr','uses'=>'PayrollController@employee_present_store']);
    Route::get('/report/bonus',['middleware'=>'check-permission:admin|hr','uses'=>'ReportController@employee_month_wise_bonus_Report']);
    Route::get('/report/increment/bonus',['middleware'=>'check-permission:admin|hr','uses'=>'ReportController@incrementBonus']);
    Route::get('/report/attendance/bonus',['middleware'=>'check-permission:admin|hr','uses'=>'ReportController@attendanceBonus']);
    Route::get('/report/festival/bonus',['middleware'=>'check-permission:admin|hr','uses'=>'ReportController@festivalBonus']);
    Route::post('/report/employee/increment',['middleware'=>'check-permission:admin|hr','uses'=>'ReportController@incrementEmployeeBonusReport']);
    Route::post('/report/employee/attendance/bonus',['middleware'=>'check-permission:admin|hr','uses'=>'ReportController@attendanceEmployeeBonusReport']);
    Route::post('/report/employee/festival/bonus',['middleware'=>'check-permission:admin|hr','uses'=>'ReportController@festivalEmloyeeBonusReport']);
    Route::post('/report/employee/increment/bonus/pdf',['middleware'=>'check-permission:admin|hr','uses'=>'ReportController@incrementreportpdf']);
    Route::post('/report/employee/attendance/bonus/pdf',['middleware'=>'check-permission:admin|hr','uses'=>'ReportController@attendancereportpdf']);
    Route::post('/report/employee/festival/bonus/pdf',['middleware'=>'check-permission:admin|hr','uses'=>'ReportController@festivalreportpdf']);

    Route::post('/report/year/bonus',['middleware'=>'check-permission:admin|hr','uses'=>'ReportController@one_year_bonus_Report']);
    Route::get('/report/payroll/employee/salary/sheet/save',['middleware'=>'check-permission:admin|hr','uses'=>'SalarySheet@view_salary_sheet']);
    Route::get('/report/payroll/employee/salary/summery',['middleware'=>'check-permission:admin|hr','uses'=>'SalarySheet@salarySummery']);
    Route::get('/report/payroll/employee/salary/sheet',['middleware'=>'check-permission:admin|hr','uses'=>'SalarySheet@monthwisesalarysheetview']);
    Route::post('/report/employee/salary/monthwise',['middleware'=>'check-permission:admin|hr','uses'=>'SalarySheet@Monthwiseemployeesalarysheet']);

resources/views/recruitment/dailyRecruitment.blade.php
@extends('layouts.master')
@section('title', 'Daily Recruitment')
@section('content')
    <div class="page-content">
        <h2><strong>Daily Recruitment Status</strong></h2>
        {{--{!! Form::open(['method'=>'GET']) !!}--}}
        {!! Form::label('date', 'Select a date: ') !!}
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">

                    {{--{!! Form::text('date',null,['class'=>'form-control date-picker', 'id'=>'datePicker' ]) !!}--}}
                    <input type="text" class="form-control" id="date" name="date"/>
                    {{--<input type='text' class="form-control" id='date' />--}}
                </div>
            </div>
        </div>
        {{--{!! Form::close() !!}--}}

        {{--@elseif(Session::has('file_size'))--}}
        {{--<p id="alert_message" class="alert alert-danger">{{ Session::get('file_size') }}</p>--}}
        {{--@endif--}}
        <div id="hid" class="row">
            @if(isset($applications))
                @include('recruitment.recruitmentStatus')

            @endif
        </div>
    </div>


    <script>
        $(function() {
            var dateVariable;
            $("#date").datepicker({
                dateFormat: 'yy-mm-dd',
                onSelect: function(dateText) {
                    dateVariable = dateText;
//                    alert($("#date").val())

                },
            
                onClose:function () {

                    $.ajax({
                        url:"status/"+dateVariable,
                        method:'GET',
                        dataType:'html',
                        success: function (response) {
                            $('#hid').html(response);

                        },
                        error:function () {
//                            alert('error')

                        }

                    });
//                    document.getElementById('hid').style.display='block';

                }

            });

        });
    </script>
@include('include.copyright')
@endsection

resources/views/recruitment/indexVacancyApplication.blade.php
@extends('layouts.master')
@section('title', 'Vacancy Application')
@section('content')
    <div class="page-content">
        @if(Session::has('store'))
            <p id="alert_message" class="alert alert-success">{{ Session::get('store') }}</p>
        @endif
        @if(Session::has('del'))
            <p id="alert_message" class="alert alert-success">{{ Session::get('del') }}</p>
        @endif
        {{--@elseif(Session::has('file_size'))--}}
            {{--<p id="alert_message" class="alert alert-danger">{{ Session::get('file_size') }}</p>--}}
        {{--@endif--}}
        <div class="row">
            <div class="col-lg-12 portlets">
                <div class="panel">
                    <div class="panel-header">
                        <h3><i class="fa fa-table"></i> <strong>Application </strong> List</h3>
                    </div>
                    <a href="{{route('application.create')}}" class="btn custom-btn btn-xs ">Add New</a>
                    <div class="panel-content pagination2 table-responsive">
                        <table class="table table-hover table-dynamic">
                            <thead>
                            <tr>
                                <th>id</th>
                                <th>Name</th>
                                <th>Phone</th>
                                <th>Position</th>
                                <th>Submitted Date</th>
                                <th>Interview Status</th>
                                <th>Interview Date</th>
                                <th>Priority</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($applications as $a)
                                <tr>
                                    <td>{{$a->id}}</td>
                                    <td>{{$a->name}}</td>
                                    <td>{{$a->phone}}</td>
                                    <td>{{$a->vacTitle}}</td>
                                    <td>{{\Carbon\Carbon::parse($a->submittedDate)->format('Y-m-d')}}</td>
                                    <td>{{$a->interviewStatus}}</td>
                                    <td>@if($a->interviewDate!=null)
                                        {{ \Carbon\Carbon::parse($a->interviewDate)->format('Y-m-d')}}
                                    @endif
                                    </td>
                                    <td>{{$a->priorityStatus}}</td>
                                    <td>
                                        <a href="{{route('application.details',$a->id)}}" class="btn btn-default btn-sm"><i class="fa fa-eye"></i></a>
                                    </td>

                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="edit-modal" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Modal Header</h4>
                </div>
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">

                        {!! Form::open(['method'=>'POST','action'=>'RecruitmentController@storeVacancyApplication','files'=>true]) !!}

                        <div class="row">
                            <div class="col-sm-6">
                                <div class="required form-group">
                                    {!! Form::label('name','Name',['class'=>'control-label']) !!}
                                    <div class="append-icon">
                                        <input type="text" name="name" class="form-control" placeholder="Enter Name..." required>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    {!! Form::label('phone','Phone Number',['class'=>'control-label']) !!}
                                    <div class="append-icon">
                                        <input type="text" name="phone" class="form-control" placeholder="Enter Phone Number">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label class="required form-label">Applying For </label>
                                    <div class="option-group">
{{--                                        {!! Form::select('vacancy_id',[''=>'Select Vacancy Position']+ $vacancies,null,['class'=>'form-control','required'=>'']) !!}--}}

                                    </div>
                                </div>
                            </div>

                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label class="required form-label">Submitted Date</label>
                                    <div class="prepend-icon">
                                        <input type="text" name="submittedDate" class="date-picker form-control" value="{{\Carbon\Carbon::now()->format('m/d/Y')}}" required>
                                        <i class="icon-calendar"></i>
                                    </div>
                                </div>
                            </div>
                        </div>


                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label class="required form-label">Attachment (Max Size:5mb)</label>
                                    {!! Form::file('attachment', ['class'=>'form-control','required'=>'']) !!}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label class="control-label">Interview Status</label>
                                    <div class="option-group">
                                        <select id="language" onchange="interviewCheck(this);" name="interviewStatus" class="form-control">
                                            <option value="">Select Status</option>
                                            <option value="Accepted">Accepted</option>
                                            <option value="Rejected">Rejected</option>

                                        </select>
                                    </div>
                                </div>
                            </div>

                            <div id="interviewDate" class="col-sm-6">
                                <div class="form-group">
                                    <label class="form-label">Interview Date</label>
                                    <div class="prepend-icon">
                                        <input type="text" name="interviewDate" class="date-picker form-control" placeholder="Select a date...">
                                        <i class="icon-calendar"></i>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div id="conditionDisplay">
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label class="control-label">Interview Details</label>
                                        <div class="append-icon">
                                            <textarea name="interviewNote" class="form-control" placeholder="Enter the interview details..." rows="4"></textarea>
                                            <i class="icon-lock"></i>
                                        </div>
                                    </div>
                                </div>

                            </div>

                            <div class="row">


                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label class="control-label">Priority</label>
                                        <div class="option-group">
                                            <select id="language" name="priorityStatus" class="form-control">
                                                <option value="">Select Priority</option>
                                                <option value="High">High</option>
                                                <option value="Regular">Regular</option>
                                                <option value="Low">Low</option>

                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label class="control-label">Job Status</label>
                                        <div class="option-group">
                                            <select id="language" name="jobStatus" class="form-control">
                                                <option value="">Select Status</option>
                                                <option value="Confirm">Confirm</option>
                                                <option value="WaitingList">Waiting List</option>
                                                <option value="Reject">Reject</option>

                                            </select>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>



                        <div class="text-center  m-t-20">
                            <button type="submit" class="btn btn-embossed btn-primary">Save</button>
                            <button type="reset" class="cancel btn btn-embossed btn-default m-b-10 m-r-0">Cancel</button>
                        </div>
                        {!! Form::close() !!}

                    </div>
                </div>
            </div>

        </div>
    </div>



    <script>
//        $('.show-edit-modal').click(function (event){
//            event.preventDefault();
//            $('#edit-modal').modal('show');
//
//        });


        setTimeout(function() {
            $('#alert_message').fadeOut('fast');

        }, 5000);
    </script>


    @include('include.copyright')
@endsection

resources/views/recruitment/recruitmentStatus.blade.php
<div class="panel">
    <div class="panel-header">
        <h3><i class="fa fa-table"></i> <strong>Application </strong> List</h3>
    </div>
    <div class="panel-content pagination2 table-responsive">
        <table class="table table-hover table-dynamic">
            <thead>
            <tr>
                <th>id</th>
                <th>Name</th>
                <th>Phone</th>
                <th>Position</th>
                <th>Submitted Date</th>
                <th>Interview Status</th>
                <th>Interview Date</th>
                <th>Priority</th>
                {{--<th>Joining Date</th>--}}
                {{--<th>Status</th>--}}
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            @foreach($applications as $a)
                <tr>
                    <td>{{$a->id}}</td>
                    <td>{{$a->name}}</td>
                    <td>{{$a->phone}}</td>
                    <td>{{$a->vacTitle}}</td>
                    <td>{{\Carbon\Carbon::parse($a->submittedDate)->format('Y-m-d')}}</td>
                    <td>{{$a->interviewStatus}}</td>
                    <td>{{\Carbon\Carbon::parse($a->interviewDate)->format('Y-m-d')}}</td>
                    <td>{{$a->priorityStatus}}</td>
                    <td>
                        <a href="{{route('application.details',$a->id)}}" class="btn btn-default btn-sm"><i class="fa fa-eye"></i></a>
                        {{--<button type="button" class="btn btn-info btn-xs show-edit-modal" data-toggle="modal" data-target="edit{{$a->id}}">Open</button>--}}
                    </td>

                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
</div>

resources/views/recruitment/vacancyList.blade.php
@extends('layouts.master')
@section('title', 'Vacancy List')
@section('content')
    <div class="page-content">
        @if(Session::has('store'))
            <p id="alert_message" class="alert alert-success">{{ Session::get('store') }}</p>
        @elseif(Session::has('msg'))
            <p id="alert_message" class="alert alert-danger">{{ Session::get('msg') }}</p>

        @endif
        <div class="row">
            <div class="col-lg-12 portlets">
                <div class="panel">
                    <div class="panel-header">
                        <h3><i class="fa fa-table"></i> <strong>Vacancy </strong> List</h3>
                    </div>
                    <a href="{{route('vacancy.create')}}" class="btn custom-btn btn-xs ">Add New</a>
                    <div class="panel-content pagination2 table-responsive">
                        <table class="table table-hover table-dynamic">
                            <thead>
                            <tr>
                                <th>Id</th>
                                <th>Title</th>
                                <th>Vacancy No.</th>
                                <th>Start Date</th>
                                <th>End Date</th>
                                <th>Joining Date</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($vacancies as $v)
                                <tr>
                                    <td>{{$v->id}}</td>
                                    <td>{{$v->vacTitle}}</td>
                                    <td>{{$v->vacNumber}}</td>
                                    <td>{{\Carbon\Carbon::parse($v->VacAnnounceStartingDate)->format('Y-m-d')}}</td>
                                    <td>{{\Carbon\Carbon::parse($v->vacAnnounceEndingDate)->format('Y-m-d')}}</td>
                                    <td>{{\Carbon\Carbon::parse($v->vacJoiningDate)->format('Y-m-d')}}</td>
                                    <td>
                                        @if($v->vacStatus==1)
                                            Active
                                        @endif
                                        @if($v->vacStatus==0)
                                            <span class="text-red">Inactive</span>
                                        @endif
                                    </td>

                                    <td>
                                        <a href="{{route('vacancy.show',$v->id)}}" class="btn btn-default btn-sm"><i class="fa fa-eye"></i></a>
                                    </td>

                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <script>
        setTimeout(function() {
            $('#alert_message').fadeOut('fast');
        }, 5000);
    </script>


    @include('include.copyright')
@endsection