routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Route for home login page and redirect to dashboard


Route::get('/','dashboardcontroller@dashboard_view');
Route::get('/dashboard','dashboardcontroller@dashboard_view');
Auth::routes();
//all necessary command
Route::get('commands', function () {
    \Artisan::call('migrate');
    return Redirect::back();
});

Route::get('/404', function () {
    return view('404_error');
});

Route::get('/info', function () {
    return view('phpinfo');
});

Route::get('/error', function () {
    return view('404');
});

Route::get('/500', function () {
    return view('404_error');
});

Route::get('/logout', 'Auth\LoginController@logout');
Route::get('/employee/details/{id}','EmployeeController@show');
//Route::get('/leave_show','leaveController@leave_type_show');
//Role wise permission route
Route::group(['middleware'=>'auth'], function () {
    //test
    Route::get('/arafat/up',['uses'=>'CountryController@up']);

    //quota
    Route::get('/quota_district_list',['middleware'=>'check-permission:admin|hr|executive','uses'=>'QuotaController@district_list'])->name('quota.district_list');
    Route::get('/quota_settings',['middleware'=>'check-permission:admin|hr|executive','uses'=>'QuotaController@quota_settings'])->name('quota.settings');
    Route::post('/quota_settings',['middleware'=>'check-permission:admin|hr|executive','uses'=>'QuotaController@store_district']);
    Route::post('/store_vacancy',['middleware'=>'check-permission:admin|hr|executive','uses'=>'QuotaController@store_vacancy']);
    Route::patch('/quota_settings/{id}',['middleware'=>'check-permission:admin|hr|executive','uses'=>'QuotaController@update_district']);
    Route::get('/quota_population',['middleware'=>'check-permission:admin|hr|executive','uses'=>'QuotaController@population'])->name('quota.population');
    Route::post('/quota_population',['middleware'=>'check-permission:admin|hr|executive','uses'=>'QuotaController@store_population']);
    Route::patch('/quota_population/{id}',['middleware'=>'check-permission:admin|hr|executive','uses'=>'QuotaController@update_population']);


    //all training route start
    Route::get('/add_training',['middleware'=>'check-permission:admin|hr|executive','uses'=>'TrainingController@index']);
    Route::post('/add_training',['middleware'=>'check-permission:admin|hr|executive','uses'=>'TrainingController@storeTraining']);
    Route::post('/training_update',['middleware'=>'check-permission:admin|hr|executive','uses'=>'TrainingController@trainingUpdate']);
    Route::post('/employee_training',['middleware'=>'check-permission:admin|hr|executive','uses'=>'TrainingController@employeeTraining']);
    Route::get('/training_delete/{id}',['middleware'=>'check-permission:admin|hr|executive','uses'=>'TrainingController@training_delete']);
    Route::get('/training_history',['middleware'=>'check-permission:admin|hr|executive','uses'=>'TrainingController@training_history']);
    Route::get('/assign/training',['middleware'=>'check-permission:admin|hr','uses'=>'TrainingController@training_assign']);
    Route::get('/assign/training/des_table/{designation}', 'TrainingController@DesignationTable');
    Route::get('/training/history/attendent/{id}', 'TrainingController@AttendentList');
    Route::get('/assign/training/addEmployee/{empid}', 'TrainingController@EmployeeTable');
    Route::get('/assign/training/delete/{del}', 'TrainingController@DeleteFromnTable');
    Route::post('/training/assign',['middleware'=>'check-permission:admin|hr','uses'=>'TrainingController@training_assign_request']);
    //training route end

    //Dashboard 
    Route::get('/meetingdetails/{id}','WorkingExperienceController@showDelete')->name('workexperience.delete.show');

    //Employee route start
    Route::get('/grid_view',['middleware'=>'check-permission:admin|hr|executive','uses'=>'EmployeeController@grid_view_index']);
    Route::POST('/employee_grid_filter',['middleware'=>'check-permission:admin|hr|executive','uses'=>'EmployeeController@grid_filter']);
    Route::POST('/employee_grid_search',['middleware'=>'check-permission:admin|hr|executive','uses'=>'EmployeeController@grid_employee_search']);

    Route::POST('/employee_filter',['middleware'=>'check-permission:admin|hr|executive','uses'=>'EmployeeController@filter']);
    Route::POST('/employee_search',['middleware'=>'check-permission:admin|hr|executive','uses'=>'EmployeeController@employee_search']);

    Route::get('/active_employee',['middleware'=>'check-permission:admin|hr|executive','uses'=>'EmployeeController@active_employee_list']);
    Route::POST('/active_employee_filter',['middleware'=>'check-permission:admin|hr|executive','uses'=>'EmployeeController@filter_active_employee']);
    Route::POST('/active_employee_search',['middleware'=>'check-permission:admin|hr|executive','uses'=>'EmployeeController@active_employee_search']);


    Route::get('/inactive_employee',['middleware'=>'check-permission:admin|hr|executive','uses'=>'EmployeeController@inactive_employee_list']);
    Route::POST('/inactive_employee_filter',['middleware'=>'check-permission:admin|hr|executive','uses'=>'EmployeeController@filter_inactive_employee']);
    Route::POST('/inactive_employee_search',['middleware'=>'check-permission:admin|hr|executive','uses'=>'EmployeeController@inactive_employee_search']);


    Route::get('/male_employee',['middleware'=>'check-permission:admin|hr|executive','uses'=>'EmployeeController@male_employee_list']);
    Route::POST('/male_employee_filter',['middleware'=>'check-permission:admin|hr|executive','uses'=>'EmployeeController@filter_male_employee']);
    Route::POST('/male_employee_search',['middleware'=>'check-permission:admin|hr|executive','uses'=>'EmployeeController@male_employee_search']);


    Route::get('/female_employee',['middleware'=>'check-permission:admin|hr|executive','uses'=>'EmployeeController@female_employee_list']);
    Route::POST('/female_employee_filter',['middleware'=>'check-permission:admin|hr|executive','uses'=>'EmployeeController@filter_female_employee']);
    Route::POST('/female_employee_search',['middleware'=>'check-permission:admin|hr|executive','uses'=>'EmployeeController@female_employee_search']);



    Route::post('/employee_discontinuation',['middleware'=>'check-permission:admin|hr','uses'=>'EmployeeController@UpdateResignationDate']);
    Route::resource('/employee','EmployeeController');
    Route::get('/user/profile',['middleware'=>'check-permission:admin|hr|executive|accountant','uses'=>'dashboardcontroller@user_profile'])->name('user.profile');

    Route::resource('/employee/education','EmployeeEducationInfoController',['except'=>['index','show','edit']]);
    Route::resource('/employee/training','EmployeeTrainingController',['except'=>['index','show']]);
    Route::resource('/employee/nominee','NomineeController',['except'=>['index','show']]);
    Route::resource('/employee/workexpericence','WorkingExperienceController',['except'=>['show']]);
    Route::resource('/employee/skill','SkillTestController',['except'=>['show']]);
    Route::get('/employee/workexperience/delete/{id}','WorkingExperienceController@showDelete')->name('workexperience.delete.show');
    Route::get('/employee/skill/delete/{id}','SkillTestController@showDelete')->name('skill.delete.show');
    Route::get('/employee/nominee/delete/{id}','NomineeController@showDelete')->name('nominee.delete.show');
    Route::get('/employee/training/delete/{id}','EmployeeTrainingController@showDelete')->name('training.delete.show');
    Route::resource('/employee/attachments','OtherAttachmentController',['except'=>['create','index']]);
    Route::patch('/employee/password/{id}','EmployeeController@UpdatePassword')->name('employee.password.update');
    Route::patch('/employee/photo/{id}','EmployeeController@UpdatePhoto');
//    Route::get('/employee/floor/line/{id}','EmployeeController@floor_line');
    Route::get('/employeelist/continuedAbsentList',['middleware'=>'check-permission:admin|hr','uses'=>'EmployeeController@getContinueAbsentList'])->name('employee.continued_absent_list');
    Route::post('/report/continuedAbsentListNotification',['middleware'=>'check-permission:admin|hr','uses'=>'EmployeeController@continueAbsentEmployeeNotification']);
    Route::get('section-autocomplete-ajax',array('as'=>'employee.section.autocomplete.ajax','uses'=>'EmployeeController@sectionAjaxData'));
    Route::POST('/store_medical_history',['middleware'=>'check-permission:admin|hr|executive','uses'=>'EmployeeController@store_medical_history']);
    Route::patch('/update_medical_history/{id}','EmployeeController@update_medical_history');
    Route::get('/employee_medical_history_pdf/{id}',['middleware'=>'check-permission:admin|hr|executive','uses'=>'EmployeeController@download_ems'])->name('employee.download_ems');
  
    Route::get('/AbsentEmployees/sendAutoSMS','EmployeeController@sent_auto_sms')->name('employee.continue_absent_list_autosms');
    Route::get('/retire/employee/list',['middleware'=>'check-permission:admin|hr|executive','uses'=>'EmployeeController@retired_list']);
    //Employee Route End
    //Settings route start
    Route::get('/user_settings',['middleware'=>'check-permission:admin|hr','uses'=>'SystemsettingsController@index']);
    Route::post('/user_update',['middleware'=>'check-permission:admin|hr','uses'=>'SystemsettingsController@user_pass_update']);
    Route::resource('/settings/country','CountryController',['except'=>['show','create','edit']]);
    Route::resource('/settings/maritialstatus','MaritialStatusController',['except'=>['show','create','edit']]);

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    //
}

resources/views/employee/filter_employee_list.blade.php
@extends('layouts.master')
@section('title', 'Employee List')
@section('content')
{{ Html::script('hrm_script/js/bootstrap3-typeahead.js') }}
<div class="page-content">
    <div class="row">
        <div class="col-lg-12 portlets">
            <div class="panel">
                <div class="panel-header">
                    <div class="row">
                        <div class="col-md-6">
                            <h3 ><i class="fa fa-users "></i> <strong>Employee </strong> List</h3>
                            
                        </div>
                        <div class="col-md-6" style="margin-top:8px;">
                            <a href="#"  data-toggle="modal" data-target="#filter" class="btn btn-danger btn-round btn-sm"  style="float:right;" ><i class="fa fa-filter"></i> Filter </a>
                        </div>
                    </div>

                </div>
                <div class="panel-content pagination2 table-responsive">
                    <table class="table table-hover table-dynamic table-bordered">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Employee Id</th>
                                <th>Designation</th>
                                <th>Department</th>
                                <th>Unit</th>
                                <th>Section</th>
                                <th>Joining Date</th>
                                <th>Gender</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($employees as $employee)
                            <tr>
                                <td>{{$employee->empFirstName ." ".$employee->empLastName}}</td>
                                <td>{{$employee->employeeId}}</td>
                                <td>{{$employee->designation}}</td>
                                <td>{{$employee->departmentName}}</td>
                                <td>{{$employee->unitName}}</td>
                                <td>{{$employee->empSection}}</td>
                                <td>{{\Carbon\Carbon::parse($employee->empJoiningDate)->format('Y-m-d')}}</td>
                                <td>
                                    @if($employee->empGenderId==1)
                                    Male
                                    @endif
                                    @if($employee->empGenderId==2)
                                    Female
                                    @endif
                                    @if($employee->empGenderId==3)
                                    Other
                                    @endif
                                </td>

                                <td>
                                    <a href="{{route('employee.show',$employee->id)}}"   title="View Employee Details" class="btn btn-default btn-sm"><i class="fa fa-eye"></i></a>
                                </td>

                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>



<div class="modal fade" id="filter" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"><strong>Filter Data</strong></h4>
            </div>
            <div class="modal-body" style="border-top:1px solid #ddd;">
             <form action="{{url('/employee_filter')}}" method="POST">
                {{ csrf_field() }}

                <div class="form-group">
                  <label for="departmentId">Employee Department</label>
                  <select name="departmentId" id="departmentId" class="form-control" >
                    <option value="">All Department</option>
                    @foreach($departments as $department)

                    <?php if(isset($request)&&!empty($request)){ ?>
                    <option <?php if($request->departmentId==$department->id){ echo "selected"; } ?> value="{{$department->id}}">{{$department->departmentName}}</option>
                    <?php }else{ ?>
                    <option value="{{$department->id}}">{{$department->departmentName}}</option>
                    <?php } ?>

                    @endforeach
                </select>
            </div>
            <div class="form-group">
              <label for="designationId">Employee Designation</label>
              <select name="designationId" id="designationId" class="form-control" >
                <option value="">All Designation</option>
                @foreach($designations as $d)

                <?php if(isset($request)&&!empty($request)){ ?>
                <option <?php if($request->designationId==$d->id){ echo "selected"; } ?> value="{{$d->id}}">{{$d->designation}}</option>
                <?php }else{ ?>
                <option value="{{$d->id}}">{{$d->designation}}</option>
                <?php } ?>
                @endforeach
                </select>
            </div>

            <div class="form-group">
              <label for="unitId">Branch</label>
              <select name="unitId" id="unitId" class="form-control" >
                <option value="">All Branch</option>
                @foreach($units as $unit)

                <?php if(isset($request)&&!empty($request)){ ?>
                <option <?php if($request->unitId==$unit->id){ echo "selected"; } ?> value="{{$unit->id}}">{{$unit->name}}</option>
                <?php }else{ ?>
                <option value="{{$unit->id}}">{{$unit->name}}</option>
                <?php } ?>
                @endforeach
                </select>
            </div>

            <div class="form-group">
              <label for="empSection">Employee Section</label>

                <?php if(isset($request)&&!empty($request)){ ?>
                    <input name="empSection" value="{{$request->empSection}}" id="empSection" class="form-control" >
                <?php }else{ ?>
                    <input name="empSection" placeholder="Employee Section" id="empSection" class="form-control" >
                <?php } ?>
        </div>

        <hr>
        <div class="form-group">
            <button type="submit" class="btn btn-danger" ><i class="fa fa-filter"></i> Filter</button>
            <button type="button" class="btn btn-default" data-dismiss="modal"> Close</button>
        </div>
        {!! Form::close() !!}
    </div>
</div>

</div>
</div>


<script type="text/javascript">

    var url = "{{ route('employee.section.autocomplete.ajax') }}";

    $('#empSection').typeahead({

        source:  function (query, process) {

            return $.get(url, { query: query }, function (data) {

                return process(data);

            });

        }

    });

</script>
@include('include.copyright')
@endsection

resources/views/employee/floor_lines.blade.php
{!! Form::select('line_id', $lines,null,['class'=>'form-control']) !!}

resources/views/employee/grid_index.blade.php
@extends('layouts.master')
@section('title', 'Employee List')
@section('content')
{{ Html::script('hrm_script/js/bootstrap3-typeahead.js') }}
<div class="page-content">
    <div class="row">
        <div class="col-lg-12 portlets">
            <div class="panel">
                <div class="panel-header">
                    <div class="row">
                        <div class="col-md-6">
                            <h3 ><i class="fa fa-users "></i> <strong>Employee </strong> List</h3>
                            
                        </div>
                        <div class="col-md-6" style="margin-top:8px;">
                            <a href="{{route('employee.create')}}" class="btn btn-primary btn-round btn-sm"  style="float:right;" ><i class="fa fa-plus"></i> Add New Employee</a>
                            <a href="{{route('employee.index')}}" class="btn btn-info btn-round btn-sm"  style="float:right;" ><i class="fa fa-list"></i> List View</a>
                            <a href="#"  data-toggle="modal" data-target="#filter" class="btn btn-danger btn-round btn-sm"  style="float:right;" ><i class="fa fa-filter"></i> Filter </a>
                            <a href="#"  data-toggle="modal" data-target="#search_employee" class="btn btn-success btn-round btn-sm"  style="float:right;" ><i class="fa fa-search"></i> Search Employee </a>
                        </div>


                    </div>

                </div>
                <div class="panel-content">
                        <div class="row">
                            @foreach($employees as $employee)
                                <div class="col-lg-4 col-sm-6">
                                   <a href="{{route('employee.show',$employee->id)}}"   title="View Employee Details" target="_BLANK" >
                                  <div class="panel widget-member" style="color:black !important;background:#eeeeeeab;">
                                    <div class="row">
                                      <div class="col-xs-3">
                                      <br />
                                      <img class="pull-left img-responsive" src="
                                            @if($employee->empPhoto ==null)
                                        @if($employee->empGenderId==1 || $employee->empGenderId==3)
                                        {{asset("Employee_Profile_Pic/male.png")}}
                                        @endif
                                        @if($employee->empGenderId==2)
                                        {{asset("Employee_Profile_Pic/female.jpg")}}
                                        @endif

                                        @endif
                                        @if($employee->empPhoto!=null)
                                        {{asset("Employee_Profile_Pic/".$employee->empPhoto)}}
                                        @endif
                                        ">
                                      </div>
                                      <div class="col-xs-9">
                                        <h3 class="m-t-0 member-name"><strong>{{$employee->empFirstName ." ".$employee->empLastName}}</strong></h3>
                                        <p class="member-job">
                                        @if($employee->departmentName!=null)
                                            <i class="fa fa-server c-gray-light p-r-10" style="color:black;"></i>  <b>{{$employee->departmentName}}</b>
                                        @else
                                            &nbsp;
                                        @endif
                                        </p>
                                        <p class="member-job"><i class="fa fa-anchor c-gray-light p-r-10" style="color:black;"></i> <b>{{$employee->designation}}</b></p>
                                        <div class="row">
                                          <div class="col-xlg-6 col-lg-12 col-sm-6">
                                            <p><i class="fa fa-credit-card c-gray-light p-r-10" style="color:black;"></i> {{$employee->employeeId}}</p>
                                            <p><i class="icon-calendar c-gray-light p-r-10" style="color:black;"></i> {{\Carbon\Carbon::parse($employee->empJoiningDate)->format('Y-m-d')}}</p>
                                          </div>
                                          <div class="col-xlg-6 col-lg-12 col-sm-6 align-right">
                                            <p><i class="fa fa-phone c-gray-light p-r-10" style="color:black;"></i> {{$employee->empPhone}}</p>
                                            <p><i class="fa fa-codepen c-gray-light p-r-10" style="color:black;"></i> {{$employee->empSection}}</p>
                                          </div>
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                  </a>
                                </div>

                            @endforeach

                        <div class="col-md-12 col-lg-12 col-sm-12">
                        <hr>
                            <center> {{$employees->links()}}</center>                        
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="filter" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"><strong>Filter Data</strong></h4>
            </div>
            <div class="modal-body" style="border-top:1px solid #ddd;">
             <form action="{{url('/employee_grid_filter')}}" method="POST">
                {{ csrf_field() }}

                <div class="form-group">
                  <label for="departmentId">Employee Department</label>
                  <select name="departmentId" id="departmentId" class="form-control" >
                    <option value="">All Department</option>
                    @foreach($departments as $department)

                    <?php if(isset($request)&&!empty($request)){ ?>
                    <option <?php if($request->departmentId==$department->id){ echo "selected"; } ?> value="{{$department->id}}">{{$department->departmentName}}</option>
                    <?php }else{ ?>
                    <option value="{{$department->id}}">{{$department->departmentName}}</option>
                    <?php } ?>

                    @endforeach
                </select>
            </div>
            <div class="form-group">
              <label for="designationId">Employee Designation</label>
              <select name="designationId" id="designationId" class="form-control" >
                <option value="">All Designation</option>
                @foreach($designations as $d)

                <?php if(isset($request)&&!empty($request)){ ?>
                <option <?php if($request->designationId==$d->id){ echo "selected"; } ?> value="{{$d->id}}">{{$d->designation}}</option>
                <?php }else{ ?>
                <option value="{{$d->id}}">{{$d->designation}}</option>
                <?php } ?>
                @endforeach
                </select>
            </div>

            <div class="form-group">
              <label for="unitId">Branch</label>
              <select name="unitId" id="unitId" class="form-control" >
                <option value="">All Branch</option>
                @foreach($units as $unit)

                <?php if(isset($request)&&!empty($request)){ ?>
                <option <?php if($request->unitId==$unit->id){ echo "selected"; } ?> value="{{$unit->id}}">{{$unit->name}}</option>
                <?php }else{ ?>
                <option value="{{$unit->id}}">{{$unit->name}}</option>
                <?php } ?>
                @endforeach
                </select>
            </div>

            <div class="form-group">
              <label for="empSection">Employee Section</label>

                <?php if(isset($request)&&!empty($request)){ ?>
                    <input name="empSection" value="{{$request->empSection}}" id="empSection" class="form-control" >
                <?php }else{ ?>
                    <input name="empSection" placeholder="Employee Section" id="empSection" class="form-control" >
                <?php } ?>
        </div>

        <hr>
        <div class="form-group">
            <button type="submit" class="btn btn-danger" ><i class="fa fa-filter"></i> Filter</button>
            <button type="button" class="btn btn-default" data-dismiss="modal"> Close</button>
        </div>
        {!! Form::close() !!}
    </div>
</div>

</div>
</div>


<div class="modal fade" id="search_employee" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"><strong>Search Employee</strong></h4>
            </div>
            <div class="modal-body" style="border-top:1px solid #ddd;">
             <form action="{{url('/employee_grid_search')}}" method="POST">
                {{ csrf_field() }}

                <div class="form-group">
                  <label for="employeeInfo">Keyword</label>
                  <input name="keyword" placeholder="Write search keyword here." id="employeeInfo" class="form-control" />
                </div>
            <hr>
            <div class="form-group">
                <button type="submit" class="btn btn-success" ><i class="fa fa-search"></i> Search</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fa fa-close"></i> Close</button>
            </div>
        {!! Form::close() !!}
    </div>
</div>

</div>
</div>


<script type="text/javascript">

    var url = "{{ route('employee.section.autocomplete.ajax') }}";

    $('#empSection').typeahead({

        source:  function (query, process) {

            return $.get(url, { query: query }, function (data) {

                return process(data);

            });

        }

    });

</script>
@include('include.copyright')
@endsection